/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.j;

import javax.swing.JOptionPane;

/**
 *
 * @author D-12
 */
public class JJ extends javax.swing.JFrame {

    /**
     * Creates new form JJ
     */
    public JJ() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnplain = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btcmessagedialog = new javax.swing.JButton();
        btninputdialog = new javax.swing.JButton();
        btndialogkonfirmasi = new javax.swing.JButton();
        btndialogpilihan = new javax.swing.JButton();
        btnerrormessage = new javax.swing.JButton();
        btninformasimessage = new javax.swing.JButton();
        btnwarningmessage = new javax.swing.JButton();
        btnquestionmessage = new javax.swing.JButton();
        btncancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnplain.setText("Plain Mesaage");
        btnplain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnplainActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("JOptionPane pada GUI");

        btcmessagedialog.setText("Message Dialog");
        btcmessagedialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcmessagedialogActionPerformed(evt);
            }
        });

        btninputdialog.setText("Input Dialog");
        btninputdialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninputdialogActionPerformed(evt);
            }
        });

        btndialogkonfirmasi.setText("Dialog Konfirmasi");
        btndialogkonfirmasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndialogkonfirmasiActionPerformed(evt);
            }
        });

        btndialogpilihan.setText("Dialog Pilihan");
        btndialogpilihan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndialogpilihanActionPerformed(evt);
            }
        });

        btnerrormessage.setText("Error Message");
        btnerrormessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnerrormessageActionPerformed(evt);
            }
        });

        btninformasimessage.setText("Informasi Message");
        btninformasimessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninformasimessageActionPerformed(evt);
            }
        });

        btnwarningmessage.setText("Warning Mesaage");
        btnwarningmessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnwarningmessageActionPerformed(evt);
            }
        });

        btnquestionmessage.setText("Question Message");
        btnquestionmessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnquestionmessageActionPerformed(evt);
            }
        });

        btncancel.setText("Cancel");
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnwarningmessage)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnerrormessage)
                        .addComponent(btndialogkonfirmasi)
                        .addComponent(btcmessagedialog)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btninputdialog)
                    .addComponent(btndialogpilihan)
                    .addComponent(btninformasimessage)
                    .addComponent(btnquestionmessage))
                .addGap(26, 26, 26))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(102, 102, 102))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnplain)
                        .addGap(144, 144, 144))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btncancel)
                        .addGap(161, 161, 161))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btnplain)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btcmessagedialog)
                    .addComponent(btninputdialog))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btndialogkonfirmasi)
                    .addComponent(btndialogpilihan))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnerrormessage)
                    .addComponent(btninformasimessage))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnwarningmessage)
                    .addComponent(btnquestionmessage))
                .addGap(18, 18, 18)
                .addComponent(btncancel)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnplainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnplainActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Maaf,Kamu Harus Gay","Plain Mesaage",JOptionPane.PLAIN_MESSAGE) ;
    }//GEN-LAST:event_btnplainActionPerformed

    private void btcmessagedialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcmessagedialogActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,"Ini adalah Dialog");
    }//GEN-LAST:event_btcmessagedialogActionPerformed

    private void btninputdialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninputdialogActionPerformed
        // TODO add your handling code here:
        String inputku = JOptionPane.showInputDialog("Inputkan Sesuatu");
        JOptionPane.showMessageDialog(this,"Kamu Menginputkan : " + inputku);
    }//GEN-LAST:event_btninputdialogActionPerformed

    private void btndialogkonfirmasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndialogkonfirmasiActionPerformed
        // TODO add your handling code here:
        int answer = JOptionPane.showConfirmDialog(this, "Silakan Melakukan COnfirmasi");
        
        switch (answer) {
            case JOptionPane.YES_OPTION:
                JOptionPane.showMessageDialog(this, "menjawab iya");
                break;
            case JOptionPane.NO_OPTION:
                JOptionPane.showMessageDialog(this, "menjawab tidak");
                break;
                case JOptionPane.CANCEL_OPTION:
                JOptionPane.showMessageDialog(this, "menjawab cancel");
                break;

        }
    }//GEN-LAST:event_btndialogkonfirmasiActionPerformed

    private void btndialogpilihanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndialogpilihanActionPerformed
        // TODO add your handling code here:
        int asnwer = JOptionPane.showOptionDialog(this, "Ingin keluar?", "keliar", JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,null,null,null);
        if(asnwer == JOptionPane.YES_OPTION){
            JOptionPane.showMessageDialog(this, "Progam akan keluar");
            System.exit(0);
        }
    }//GEN-LAST:event_btndialogpilihanActionPerformed

    private void btnquestionmessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnquestionmessageActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Apakah anda yakin untuk keluar dari progam ini?", 
                "Question Message", JOptionPane.QUESTION_MESSAGE);
    }//GEN-LAST:event_btnquestionmessageActionPerformed

    private void btnwarningmessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnwarningmessageActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "lengkapi isian anda",
                "Warning message", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_btnwarningmessageActionPerformed

    private void btninformasimessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninformasimessageActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Masukan data dengan sesuai",
                "Pesan informasi", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btninformasimessageActionPerformed

    private void btnerrormessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnerrormessageActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Proses yang anda lakukan tidak dapat dilanjutkan",
                "Apakah Error?", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_btnerrormessageActionPerformed

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btncancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JJ().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btcmessagedialog;
    private javax.swing.JButton btncancel;
    private javax.swing.JButton btndialogkonfirmasi;
    private javax.swing.JButton btndialogpilihan;
    private javax.swing.JButton btnerrormessage;
    private javax.swing.JButton btninformasimessage;
    private javax.swing.JButton btninputdialog;
    private javax.swing.JButton btnplain;
    private javax.swing.JButton btnquestionmessage;
    private javax.swing.JButton btnwarningmessage;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
